# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      map_api_key: ${{ secrets.map_api_key }}
      weather_api_key: ${{ secrets.weather_api_key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Code Climate Coverage Action
        # You may pin to the exact commit or the version.
        # uses: paambaati/codeclimate-action@ac3f177ece9928d220a8bd1c2f1957926fd3b67e
        uses: paambaati/codeclimate-action@v3.2.0
        with:
          # Coverage command to execute
          coverageCommand: # optional, default is 
          # Custom working directory for executing the coverage command
          workingDirectory: # optional, default is 
          # Enable debugging logs for the Code Climate test reporter
          debug: # optional, default is false
          # Locations to find code coverage (Used for builds from multiple locations)
          coverageLocations: # optional, default is 
          # See https://docs.codeclimate.com/docs/configuring-test-coverage
          prefix: # optional, default is 
          # Verify the downloaded reporter's checksum and GPG signature
          verifyDownload: # optional, default is true
